import Project.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gayatri
 */


public class addnewdonor extends javax.swing.JFrame {

    /**
     * Creates new form addnewdonor
     */
    public addnewdonor() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        N2 = new javax.swing.JTextField();
        N3 = new javax.swing.JTextField();
        N4 = new javax.swing.JTextField();
        N5 = new javax.swing.JTextField();
        N6 = new javax.swing.JComboBox<>();
        N7 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        N1 = new javax.swing.JLabel();
        N8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 48)); // NOI18N
        jLabel1.setText("ADD NEW DONOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 460, -1));

        jLabel2.setFont(new java.awt.Font("ITF Devanagari", 1, 22)); // NOI18N
        jLabel2.setText("New Donor Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("ITF Devanagari", 1, 22)); // NOI18N
        jLabel3.setText("Full Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("ITF Devanagari", 1, 22)); // NOI18N
        jLabel4.setText("Mobile No.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("ITF Devanagari", 1, 22)); // NOI18N
        jLabel5.setText("   Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 120, 40));

        jLabel6.setFont(new java.awt.Font("ITF Devanagari", 1, 22)); // NOI18N
        jLabel6.setText("Blood Group");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("ITF Devanagari", 1, 22)); // NOI18N
        jLabel7.setText("Age");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("ITF Devanagari", 1, 22)); // NOI18N
        jLabel8.setText("Donated Earlier");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, -1, -1));

        N2.setFont(new java.awt.Font("Arima Koshi", 1, 20)); // NOI18N
        getContentPane().add(N2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 140, 30));

        N3.setFont(new java.awt.Font("Arima Koshi", 1, 20)); // NOI18N
        N3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N3ActionPerformed(evt);
            }
        });
        getContentPane().add(N3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 140, 30));

        N4.setFont(new java.awt.Font("Arima Koshi", 1, 20)); // NOI18N
        N4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N4ActionPerformed(evt);
            }
        });
        getContentPane().add(N4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 140, 30));

        N5.setFont(new java.awt.Font("Arima Koshi", 1, 20)); // NOI18N
        getContentPane().add(N5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 290, 140, 30));

        N6.setFont(new java.awt.Font("Arima Koshi", 1, 20)); // NOI18N
        N6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "AB+", "AB-", "O+", "O-", "B+", "B-" }));
        N6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N6ActionPerformed(evt);
            }
        });
        getContentPane().add(N6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 390, 140, 30));

        N7.setFont(new java.awt.Font("Arima Koshi", 1, 20)); // NOI18N
        N7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        N7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N7ActionPerformed(evt);
            }
        });
        getContentPane().add(N7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 490, 140, 30));

        jButton1.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("/Users/gayatri/Desktop/bb/save.png")); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, -1, -1));

        jButton2.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("/Users/gayatri/Desktop/bb/Update details.png")); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 650, -1, -1));

        jButton3.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("/Users/gayatri/Desktop/bb/Exit application.png")); // NOI18N
        jButton3.setText("CLOSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 650, -1, -1));
        getContentPane().add(N1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 70, 20));

        N8.setFont(new java.awt.Font("Arima Koshi", 1, 20)); // NOI18N
        N8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(N8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 120, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon("/Users/gayatri/Desktop/bb/Untitled design/2.png")); // NOI18N
        jLabel10.setText("jLabel10");
        jLabel10.setMaximumSize(new java.awt.Dimension(1400, 900));
        jLabel10.setMinimumSize(new java.awt.Dimension(1400, 900));
        jLabel10.setPreferredSize(new java.awt.Dimension(1400, 900));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void N4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N4ActionPerformed

    private void N3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N3ActionPerformed

    private void N6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N6ActionPerformed

    private void N7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        
        String d_id = N8.getText();
        String name = N2.getText();
        String phno =N3.getText();
        String loc = N4.getText();
        String age = N5.getText();
        String blood_grp= (String) N6.getSelectedItem();
        String donated_earlier= (String) N7.getSelectedItem();
        
        try{
            Connection con= ConnectionProvider.getCon();
            Statement st =con.createStatement();
            st.executeUpdate("insert into donor values('"+d_id+"','"+name+"','"+phno+"','"+loc+"','"+age+"','"+blood_grp+"','"+donated_earlier+"')");
            JOptionPane.showMessageDialog(null, "Successfully Added");
            setVisible(false);
            new addnewdonor().setVisible(true);
        }
        catch(Exception e){
            throw new RuntimeException("unhandled", e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new addnewdonor().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try {
            Connection con= ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select max(d_id) from donor");
            if(rs.next())
            {
                int d_id = rs.getInt(1);
                d_id=d_id+1;
                String str = String.valueOf(d_id);
                N8.setText(str);
            }
            else
                N8.setText("1");
        }
        catch (Exception e)
        {
            throw new RuntimeException("unhandled", e);
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addnewdonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addnewdonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addnewdonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addnewdonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel N1;
    private javax.swing.JTextField N2;
    private javax.swing.JTextField N3;
    private javax.swing.JTextField N4;
    private javax.swing.JTextField N5;
    private javax.swing.JComboBox<String> N6;
    private javax.swing.JComboBox<String> N7;
    private javax.swing.JLabel N8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    
}
