import java.sql.*;
import Project.ConnectionProvider;
import java.awt.print.PrinterException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gayatri
 */
public class allDonorDetails extends javax.swing.JFrame {

    /**
     * Creates new form allDonorDetails
     */
    public allDonorDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        T1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        T2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 48)); // NOI18N
        jLabel1.setText("ALL DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        T1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "d_id", "name", "phno", "loc", "age", "blood_group", "donated_earlier"
            }
        ));
        T1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        T1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(T1);
        if (T1.getColumnModel().getColumnCount() > 0) {
            T1.getColumnModel().getColumn(0).setResizable(false);
            T1.getColumnModel().getColumn(1).setResizable(false);
            T1.getColumnModel().getColumn(1).setPreferredWidth(100);
            T1.getColumnModel().getColumn(2).setResizable(false);
            T1.getColumnModel().getColumn(2).setPreferredWidth(100);
            T1.getColumnModel().getColumn(3).setResizable(false);
            T1.getColumnModel().getColumn(3).setPreferredWidth(100);
            T1.getColumnModel().getColumn(4).setResizable(false);
            T1.getColumnModel().getColumn(5).setResizable(false);
            T1.getColumnModel().getColumn(5).setPreferredWidth(100);
            T1.getColumnModel().getColumn(6).setResizable(false);
            T1.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 650, 320));

        jButton1.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("/Users/gayatri/Desktop/bb/print.png")); // NOI18N
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 680, -1, -1));

        jButton2.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("/Users/gayatri/Desktop/bb/Exit application.png")); // NOI18N
        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 680, -1, -1));

        T2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "r_id", "name", "phno", "loc", "blood_grp"
            }
        ));
        T2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        T2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(T2);
        if (T2.getColumnModel().getColumnCount() > 0) {
            T2.getColumnModel().getColumn(1).setPreferredWidth(100);
            T2.getColumnModel().getColumn(2).setPreferredWidth(100);
            T2.getColumnModel().getColumn(3).setPreferredWidth(100);
            T2.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, 470, 320));

        jLabel2.setFont(new java.awt.Font("ITF Devanagari", 1, 22)); // NOI18N
        jLabel2.setText("DONOR DETAILS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("ITF Devanagari", 1, 22)); // NOI18N
        jLabel4.setText("RECEIVER DETAILS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 200, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/gayatri/Downloads/Untitled design/2.png")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            T1.print(JTable.PrintMode.NORMAL);
        }
        catch(PrinterException e){
            JOptionPane.showMessageDialog(null, e);
        }
         try{
            T2.print(JTable.PrintMode.NORMAL);
        }
        catch(PrinterException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs= st.executeQuery("select * from donor");
            T1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            //T1.setModel(DbUtils.resultSetToTableModel(rs));
            while(rs.next()){
                String d_id = String.valueOf(rs.getInt("d_id"));
                String name = rs.getString("name");
                String phno = rs.getString("phno");
                String loc = rs.getString("loc");
                String age = String.valueOf(rs.getInt("age"));
                String blood_grp = rs.getString("blood_grp");
                String donated_earlier = rs.getString("donated_earlier");
                
                String tbData[] = {d_id,name,phno,loc,age,blood_grp,donated_earlier};
                DefaultTableModel tb1 =(DefaultTableModel)T1.getModel();
                tb1.addRow(tbData);
               
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs1= st.executeQuery("select * from receiver");
            T2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            //T1.setModel(DbUtils.resultSetToTableModel(rs));
            while(rs1.next()){
                String r_id = String.valueOf(rs1.getInt("r_id"));
                String name = rs1.getString("name");
                String phno = rs1.getString("phno");
                String loc = rs1.getString("loc");
                String blood_grp = rs1.getString("blood_grp");
                
                String tb1Data[] = {r_id,name,phno,loc,blood_grp};
                DefaultTableModel tb2 =(DefaultTableModel)T2.getModel();
                tb2.addRow(tb1Data);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(allDonorDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(allDonorDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(allDonorDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(allDonorDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new allDonorDetails().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable T1;
    private javax.swing.JTable T2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
