import java.sql.*;
import Project.ConnectionProvider;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gayatri
 */
public class deletedonor extends javax.swing.JFrame {

    /**
     * Creates new form deletedonor
     */
    public deletedonor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        N21 = new javax.swing.JTextField();
        N20 = new javax.swing.JTextField();
        N22 = new javax.swing.JTextField();
        N23 = new javax.swing.JTextField();
        N24 = new javax.swing.JTextField();
        N25 = new javax.swing.JTextField();
        N26 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 48)); // NOI18N
        jLabel1.setText("DELETE DONOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("ITF Devanagari", 1, 22)); // NOI18N
        jLabel3.setText(" Donor Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 130, -1));

        jLabel4.setFont(new java.awt.Font("ITF Devanagari", 1, 22)); // NOI18N
        jLabel4.setText("Full Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("ITF Devanagari", 1, 22)); // NOI18N
        jLabel5.setText("Mobile No.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, -1, -1));

        jLabel6.setFont(new java.awt.Font("ITF Devanagari", 1, 22)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, -1, -1));

        jLabel7.setFont(new java.awt.Font("ITF Devanagari", 1, 22)); // NOI18N
        jLabel7.setText("Age");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, -1, 40));

        jLabel8.setFont(new java.awt.Font("ITF Devanagari", 1, 22)); // NOI18N
        jLabel8.setText("Blood Group");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, -1, -1));

        jLabel9.setFont(new java.awt.Font("ITF Devanagari", 1, 22)); // NOI18N
        jLabel9.setText("Donated Earlier");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 570, -1, -1));

        N21.setFont(new java.awt.Font("Arima Koshi", 1, 20)); // NOI18N
        N21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N21ActionPerformed(evt);
            }
        });
        getContentPane().add(N21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 170, 30));

        N20.setFont(new java.awt.Font("Arima Koshi", 1, 20)); // NOI18N
        getContentPane().add(N20, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 170, 30));

        N22.setFont(new java.awt.Font("Arima Koshi", 1, 20)); // NOI18N
        getContentPane().add(N22, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 170, 30));

        N23.setFont(new java.awt.Font("Arima Koshi", 1, 20)); // NOI18N
        getContentPane().add(N23, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, 170, 30));

        N24.setFont(new java.awt.Font("Arima Koshi", 1, 20)); // NOI18N
        getContentPane().add(N24, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 360, 180, 30));

        N25.setFont(new java.awt.Font("Arima Koshi", 1, 20)); // NOI18N
        getContentPane().add(N25, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 470, 180, 30));

        N26.setFont(new java.awt.Font("Arima Koshi", 1, 20)); // NOI18N
        getContentPane().add(N26, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 570, 170, 30));

        jButton5.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("/Users/gayatri/Desktop/bb/search1.png")); // NOI18N
        jButton5.setText("SEARCH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, -1));

        jButton1.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("/Users/gayatri/Desktop/bb/delete.png")); // NOI18N
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 690, -1, -1));

        jButton2.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("/Users/gayatri/Desktop/bb/Update details.png")); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 690, -1, -1));

        jButton3.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("/Users/gayatri/Desktop/bb/Exit application.png")); // NOI18N
        jButton3.setText("CLOSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 690, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("/Users/gayatri/Downloads/Untitled design/2.png")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String d_id=N20.getText();
         try{
           Connection con = ConnectionProvider.getCon();
           Statement st=con.createStatement();
           st.executeUpdate("delete from donor where d_id='"+d_id+"'");
           JOptionPane.showMessageDialog(null, "Successfully Deleted");
           new deletedonor().setVisible(true);
         }
         catch(Exception e){
            JOptionPane.showMessageDialog(null,e); 
         }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void N21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N21ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String d_id=N20.getText();
        try{
            Connection con= ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs= st.executeQuery("select * from donor where d_id ='"+d_id+"'");
            if(rs.next()){
                N21.setText(rs.getString(2));
               N22.setText(rs.getString(3));
               N23.setText(rs.getString(4));
               N24.setText(rs.getString(5));
               N25.setText(rs.getString(6));
               N26.setText(rs.getString(7));
               N20.setEditable(false);     
           }
           else{
               JOptionPane.showMessageDialog(null,"Donor does not exist");
            }
        }
            catch(Exception e){
                    
                    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new deletedonor().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deletedonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deletedonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deletedonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deletedonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deletedonor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField N20;
    private javax.swing.JTextField N21;
    private javax.swing.JTextField N22;
    private javax.swing.JTextField N23;
    private javax.swing.JTextField N24;
    private javax.swing.JTextField N25;
    private javax.swing.JTextField N26;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
