
import Project.ConnectionProvider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gayatri
 */
public class searchBloodGroup extends javax.swing.JFrame {

    /**
     * Creates new form searchBloodGroup
     */
    public searchBloodGroup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        T4 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 48)); // NOI18N
        jLabel1.setText("SEARCH BLOOD DONOR (BLOOD GROUP)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("ITF Devanagari", 1, 22)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/gayatri/Desktop/bb/Blood group.png")); // NOI18N
        jLabel2.setText("Blood Group");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 142, -1, -1));

        bg.setFont(new java.awt.Font("Arima Koshi", 1, 20)); // NOI18N
        bg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgActionPerformed(evt);
            }
        });
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 144, 192, 34));

        T4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "d_id", "name", "phno", "loc", "age", "blood_grp", "donated_earlier"
            }
        ));
        T4.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(T4);
        if (T4.getColumnModel().getColumnCount() > 0) {
            T4.getColumnModel().getColumn(2).setPreferredWidth(100);
            T4.getColumnModel().getColumn(5).setPreferredWidth(100);
            T4.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 217, 608, -1));

        jButton1.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("/Users/gayatri/Desktop/bb/print.png")); // NOI18N
        jButton1.setText("PRINT");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 686, -1, -1));

        jButton2.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("/Users/gayatri/Desktop/bb/Exit application.png")); // NOI18N
        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(856, 686, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/gayatri/Downloads/Untitled design/2.png")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgActionPerformed
        // TODO add your handling code here:
        String blood_group = bg.getText();
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs1= st.executeQuery("select * from donor where blood_grp = '"+ blood_group+ "'");
            T4.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            //T1.setModel(DbUtils.resultSetToTableModel(rs));
            while(rs1.next()){
                String d_id = String.valueOf(rs1.getInt("d_id"));
                String name = rs1.getString("name");
                String phno = rs1.getString("phno");
                String loc = rs1.getString("loc");
                String age = String.valueOf(rs1.getInt("age"));
                String blood_grp = rs1.getString("blood_grp");
                String donated_earlier = rs1.getString("donated_earlier");
                
                String tb3Data[] = {d_id,name,phno,loc,age,blood_grp,donated_earlier};
                DefaultTableModel tb4 =(DefaultTableModel)T4.getModel();
                tb4.addRow(tb3Data);
            }
        }
        catch(SQLException e){
            javax.swing.JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_bgActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchBloodGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchBloodGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchBloodGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchBloodGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchBloodGroup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable T4;
    private javax.swing.JTextField bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
